/**
 * VerifyIQ — Gemini AI Integration
 *
 * Provides Gemini-powered analysis functions for:
 * 1. AI Content Detection (is this human or AI-written?)
 * 2. Paraphrase / Plagiarism Analysis (detect reworded copying)
 * 3. Writing Coach (grammar, clarity, style improvements)
 * 4. Authorship Fingerprint (style consistency, voice analysis)
 */

import { GoogleGenerativeAI, HarmCategory, HarmBlockThreshold } from "@google/generative-ai";

// ═══════════════════════════════════════
//  CLIENT SINGLETON
// ═══════════════════════════════════════

let _genAI: GoogleGenerativeAI | null = null;

function getClient(): GoogleGenerativeAI {
  if (!_genAI) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error("GEMINI_API_KEY is not set in environment variables.");
    _genAI = new GoogleGenerativeAI(apiKey);
  }
  return _genAI;
}

function getModel(modelName = "gemini-2.0-flash") {
  return getClient().getGenerativeModel({
    model: modelName,
    safetySettings: [
      { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_NONE },
      { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_NONE },
      { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_NONE },
      { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_NONE },
    ],
  });
}

async function callGemini(prompt: string): Promise<string> {
  const model = getModel();
  const result = await model.generateContent(prompt);
  return result.response.text();
}

function safeParseJSON<T>(text: string, fallback: T): T {
  try {
    // Strip markdown code fences if present
    const cleaned = text.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/, "").trim();
    return JSON.parse(cleaned) as T;
  } catch {
    return fallback;
  }
}

// ═══════════════════════════════════════
//  1. AI CONTENT DETECTION
// ═══════════════════════════════════════

export interface GeminiAiDetectionResult {
  aiProbability: number;       // 0–100
  humanProbability: number;    // 0–100
  verdict: "likely_human" | "mixed" | "likely_ai";
  confidence: number;          // 0–100 — how confident Gemini is
  reasoning: string;           // plain-English explanation
  aiSignals: string[];         // specific signals that suggest AI writing
  humanSignals: string[];      // specific signals that suggest human writing
  keyFindings: string[];       // bullet list of top findings
}

export async function geminiDetectAI(text: string): Promise<GeminiAiDetectionResult> {
  const truncated = text.slice(0, 4000); // stay within token limits

  const prompt = `You are an expert AI-content detector trained to distinguish between human-written and AI-generated text.

Analyze the following text and determine whether it was written by a human or generated by an AI (like ChatGPT, Gemini, Claude, etc.).

Look for these AI signals:
- Unnaturally uniform sentence structure and length
- Overly polished transitions ("Furthermore", "Moreover", "In conclusion")
- Lack of personal anecdotes, emotion, or unique voice
- Generic or formulaic phrasing
- Excessive hedging or qualifiers
- Consistent vocabulary without personality quirks

Look for these human signals:
- Varied sentence length and rhythm
- Personal opinions or informal phrasing
- Grammatical imperfections or casual language
- Unique metaphors or humor
- Emotional engagement
- Tangential thoughts or digressions

TEXT TO ANALYZE:
"""
${truncated}
"""

Return ONLY a valid JSON object (no markdown, no explanation outside JSON):
{
  "aiProbability": <0-100>,
  "humanProbability": <0-100>,
  "verdict": "<likely_human|mixed|likely_ai>",
  "confidence": <0-100>,
  "reasoning": "<2-3 sentence plain English summary>",
  "aiSignals": ["<signal1>", "<signal2>"],
  "humanSignals": ["<signal1>", "<signal2>"],
  "keyFindings": ["<finding1>", "<finding2>", "<finding3>"]
}`;

  const raw = await callGemini(prompt);
  const fallback: GeminiAiDetectionResult = {
    aiProbability: 50,
    humanProbability: 50,
    verdict: "mixed",
    confidence: 0,
    reasoning: "Unable to analyze text with AI model.",
    aiSignals: [],
    humanSignals: [],
    keyFindings: [],
  };
  return safeParseJSON(raw, fallback);
}

// ═══════════════════════════════════════
//  2. PLAGIARISM / PARAPHRASE ANALYSIS
// ═══════════════════════════════════════

export interface GeminiPlagiarismResult {
  paraphrasingDetected: boolean;
  paraphrasingScore: number;    // 0–100
  suspiciousSegments: {
    text: string;
    reason: string;
    severity: "high" | "medium" | "low";
  }[];
  overallVerdict: string;        // plain English
  suggestedActions: string[];
}

export async function geminiAnalyzePlagiarism(
  text: string,
  matchedSources: { name: string; snippet: string }[]
): Promise<GeminiPlagiarismResult> {
  const truncated = text.slice(0, 3000);
  const sourcesText = matchedSources
    .slice(0, 5)
    .map((s, i) => `Source ${i + 1} (${s.name}): "${s.snippet.slice(0, 200)}"`)
    .join("\n");

  const prompt = `You are an expert academic integrity analyzer specializing in detecting paraphrasing plagiarism.

Analyze the SUBMITTED TEXT below and check if it appears to paraphrase or rephrase content from the MATCHED SOURCES. Even if the words are different, look for:
- Same ideas expressed in different words
- Sentence structure mirroring the sources
- Same sequence of concepts
- Synonyms substituted for original words

SUBMITTED TEXT:
"""
${truncated}
"""

${matchedSources.length > 0 ? `MATCHED SOURCES (already detected with similarity algorithms):
${sourcesText}` : "No specific sources were matched by the similarity algorithm."}

Return ONLY valid JSON (no markdown):
{
  "paraphrasingDetected": <true|false>,
  "paraphrasingScore": <0-100>,
  "suspiciousSegments": [
    { "text": "<excerpt from submitted text>", "reason": "<why this is suspicious>", "severity": "<high|medium|low>" }
  ],
  "overallVerdict": "<1-2 sentence plain English summary>",
  "suggestedActions": ["<action1>", "<action2>"]
}`;

  const fallback: GeminiPlagiarismResult = {
    paraphrasingDetected: false,
    paraphrasingScore: 0,
    suspiciousSegments: [],
    overallVerdict: "Paraphrase analysis unavailable.",
    suggestedActions: [],
  };
  const raw = await callGemini(prompt);
  return safeParseJSON(raw, fallback);
}

// ═══════════════════════════════════════
//  3. WRITING COACH
// ═══════════════════════════════════════

export interface WritingCoachSuggestion {
  type: "grammar" | "clarity" | "style" | "structure" | "vocabulary" | "citation";
  severity: "error" | "warning" | "suggestion";
  original: string;
  improved: string;
  explanation: string;
}

export interface GeminiWritingCoachResult {
  overallScore: number;          // 0–100 writing quality
  grammarScore: number;
  clarityScore: number;
  styleScore: number;
  structureScore: number;
  suggestions: WritingCoachSuggestion[];
  strengths: string[];
  areasToImprove: string[];
  rewrittenIntro: string;        // Gemini rewrites the first paragraph as example
  summary: string;
}

export async function geminiWritingCoach(text: string): Promise<GeminiWritingCoachResult> {
  const truncated = text.slice(0, 4000);

  const prompt = `You are a professional academic writing coach. Analyze the following text and provide detailed, actionable writing feedback.

TEXT:
"""
${truncated}
"""

Evaluate the text on:
1. Grammar & mechanics (punctuation, spelling, verb agreement)
2. Clarity (is it easy to understand?)
3. Style (is it appropriate for academic/professional use?)
4. Structure (organization, flow, transitions)
5. Vocabulary (word choice, precision, variety)

Return ONLY valid JSON (no markdown, no extra text):
{
  "overallScore": <0-100>,
  "grammarScore": <0-100>,
  "clarityScore": <0-100>,
  "styleScore": <0-100>,
  "structureScore": <0-100>,
  "suggestions": [
    {
      "type": "<grammar|clarity|style|structure|vocabulary|citation>",
      "severity": "<error|warning|suggestion>",
      "original": "<exact quote from the text>",
      "improved": "<your improved version>",
      "explanation": "<why this change helps>"
    }
  ],
  "strengths": ["<strength1>", "<strength2>", "<strength3>"],
  "areasToImprove": ["<area1>", "<area2>", "<area3>"],
  "rewrittenIntro": "<Rewrite the first paragraph in a clearer, more engaging way>",
  "summary": "<2-3 sentence overall assessment>"
}

Provide 5-10 specific suggestions. Be constructive and encouraging.`;

  const fallback: GeminiWritingCoachResult = {
    overallScore: 0,
    grammarScore: 0,
    clarityScore: 0,
    styleScore: 0,
    structureScore: 0,
    suggestions: [],
    strengths: [],
    areasToImprove: [],
    rewrittenIntro: "",
    summary: "Writing coach analysis unavailable.",
  };
  const raw = await callGemini(prompt);
  return safeParseJSON(raw, fallback);
}

// ═══════════════════════════════════════
//  4. AUTHORSHIP FINGERPRINT
// ═══════════════════════════════════════

export interface GeminiAuthorshipResult {
  consistencyScore: number;      // 0–100
  dominantStyle: string;         // e.g. "Academic", "Informal", "Technical"
  voiceCharacteristics: string[];
  styleShifts: {
    location: string;
    description: string;
    severity: "high" | "medium" | "low";
    possibleExplanation: string;
  }[];
  writingPersonality: string;    // brief description of writing style
  authenticityVerdict: "consistent" | "mixed" | "suspicious";
  authenticityReasoning: string;
  recommendations: string[];
}

export async function geminiAuthorshipAnalysis(text: string): Promise<GeminiAuthorshipResult> {
  const truncated = text.slice(0, 5000);

  const prompt = `You are an expert in forensic linguistics and authorship verification. Analyze the writing style of the following text to determine if it was written by a single author consistently, or shows signs of multiple authors or AI-assisted writing.

TEXT:
"""
${truncated}
"""

Analyze:
1. Voice consistency (does the writing voice stay consistent throughout?)
2. Style shifts (abrupt changes in complexity, tone, formality)
3. Vocabulary patterns (consistent word choice preferences)
4. Grammatical habits (comma usage, sentence structure patterns)
5. Transition patterns (predictable vs. varied connectives)

Return ONLY valid JSON (no markdown, no extra text):
{
  "consistencyScore": <0-100>,
  "dominantStyle": "<Academic|Informal|Technical|Creative|Mixed>",
  "voiceCharacteristics": ["<characteristic1>", "<characteristic2>", "<characteristic3>"],
  "styleShifts": [
    {
      "location": "<approximately where in the text>",
      "description": "<what changed>",
      "severity": "<high|medium|low>",
      "possibleExplanation": "<why this might have happened>"
    }
  ],
  "writingPersonality": "<2-3 sentence description of the writing style and voice>",
  "authenticityVerdict": "<consistent|mixed|suspicious>",
  "authenticityReasoning": "<2-3 sentence explanation of the verdict>",
  "recommendations": ["<recommendation1>", "<recommendation2>"]
}`;

  const fallback: GeminiAuthorshipResult = {
    consistencyScore: 50,
    dominantStyle: "Unknown",
    voiceCharacteristics: [],
    styleShifts: [],
    writingPersonality: "Analysis unavailable.",
    authenticityVerdict: "mixed",
    authenticityReasoning: "Authorship analysis unavailable.",
    recommendations: [],
  };
  const raw = await callGemini(prompt);
  return safeParseJSON(raw, fallback);
}
